### ISSUE TITLE
Warning messages: In matrix(as.numeric(d)) : NAs introduced by coercion, and In cor(x, y) : the standard deviation is zero

### ISSUE THREAD

**Issue by cmontalvo-mancheno** [jamiemkass/ENMeval#105]
Hi guys! First of all thanks for your package and previous support! When tuning features and regularization multiplier, I got the following warning messages (please see screenshot_M1).
![Screenshot_M1](https://user-images.githubusercontent.com/81724937/134832414-606e9802-7d8b-4183-a6c6-29580201a19a.jpg)

Should I be worried about these warning messages? How troublesome/problematic would these warning messages be when selecting the best model (please see attached screenshot_M2)? Could these warning messages be related to the use of hinge features and/or regularization multiplier lower than 1, as noted in other reported issues (e.g., #72 and #92)?
![Screenshot_M2](https://user-images.githubusercontent.com/81724937/134832483-69ec47c4-5c56-49ac-a018-ba6e5807d1c2.jpg)

**Comment by jamiemkass** [comment]
Sorry about the late reply. Yes, I think this warning occurs when very complex models are overfit to data without complex structure. Unless you have lots of presence data spanning a broad environmental gradient, models with rm < 1 are likely too complex, especially when they include hinge or product features. Can you run this again without the very low rms and see if this warning still appears?

**Comment by jamiemkass** [comment]
Thanks so much for sending these data to me. After some investigating, two things become clear. Not sure how comprehensive these answers are, but they definitely seem to be the culprits here:

1) `Warning in matrix(as.numeric(d)) : NAs introduced by coercion`: This is caused by a model fitted (in this case, `dismo::maxent()`) with no predictors that have non-zero beta coefficients (the values in the "lambdas" slot). This can occur if the regularization is relatively high and there are few potential betas to begin with, because the regularization can remove them all. I think this most often occurs during cross-validation because each model only has a subset of the total data, and thus has a better chance of having a response so simple that this occurs.
2) `Warning in cor(x, y) : the standard deviation is zero`: This is caused by `dismo::evaluate()` called on a model like the one described above. The predictions will all be 0.5, and thus when training and validation predictions are compared, there is no difference between them, and you get this warning.

The moral of this story is: I think it's safe to ignore these model settings because they seem to be penalizing complexity too much. You should probably consider lower regularization multiplier values.

**Comment by cmontalvo-mancheno** [comment]
Thank you very much your time and feedback. I followed your advise and tried a different model setting. In this case, I replaced the user-defined partitions for cross-validation by the "randomkfold", with the number of folds set to 100. With this change, there were no warning messages. Given that this took about 920 minutes to complete, I added parallel processing to speed up the computation (i.e., about 105 minutes). At the end this is the model setting that worked for me (please see code below):
```
ENMevaluate(occs = suit_1_occs %>% select(x:y), envs = env_var_bioreg_08,
            bg = suit_1_bg %>% select(x:y),
            tune.args = list(fc = c("L", "Q", "H", "T", "P", "LQ", "LH",
                                    "LP", "LQH", "LQT", "LQHP", "LQHPT"),
                             rm = seq(from = 0.25, to = 5, by = 0.25)), 
            algorithm = 'maxent.jar', partitions ="randomkfold", doClamp = FALSE,
            partition.settings = list(kfolds = 100),
            other.settings = list(abs.auc.diff = TRUE,
                                  pred.type = "logistic",
                                  validation.bg = "full"),
            parallel = TRUE, numCores = 10, parallelType = "doSNOW")
