### ISSUE TITLE
glmnet failed to complete regularization path & glmnet Fortran code (error code -171)

### ISSUE THREAD

**Issue by EikeU** [jamiemkass/ENMeval#110]
Hi, 

I hope I am alright posting this here. I have used ENMeval as part of my Bachelor thesis and am now refining my model to hopefully publish the results.

I get following error since the update:

_Error
in (function (p, data, f = maxnet.formula(p, data), regmult = 1,  : 
  Error: glmnet failed to complete regularization path.  Model may be infeasible.
In addition: Warning message:
from glmnet Fortran code (error code -171); Convergence for 171th lambda value not reached after maxit=100000 iterations; solutions for larger lambdas returned_

My function is...

_less_80_mod <- ENMevaluate(occs = occ,          
                           envs = env,         
                           bg = bg,     
                           algorithm = "maxnet",
                           partitions = "randomkfold", 
                           tune.args = list(fc = "L", rm = 1), 
                           categorical = "Soil.Type"
                           )_

...with _occ_ a dataframe, _env_ a rasterstack and _bg_ a dataframe.

I have 38 occurrences with Long/ Lat across Borneo. The study area is whole of Borneo as well with no restriction. I cannot use buffers around occs or a smaller study area, as the dispersal capacity, dispersal and population structure is pretty much unknown about the species I am modelling. The occs I have are not representative of the actual distribution (I am aware of these limitations for my study).

I chose 10.000 background points via a bias file. However, the same error message appears when I chose my background points randomly without bias file as well. My _env_ contains 8 bioclimatic variables, elevation and soil type (categorial).

Would someone be able to help me with this? Thank you!
I am new to R and used it and SDM modelling for the first time, so the error could be also on my side.

**Comment by jamiemkass** [comment]
@EikeU, sorry you're having issues. This is a `maxnet` problem, unfortunately, and I have no idea what's wrong. You have relatively simple settings (L1), not too many variables, a relatively small study extent, and not a whole lot of occurrences. The model should not be so complicated that `glmnet` (which runs `maxnet`) fails. I would suggest you try maxent.jar if you can get it running because it does not suffer from these issues (it's written in Java and does not use `glmnet`).

**Comment by jamiemkass** [comment]
One thing is that the argument is "categoricals", not "categorical". Wonder if this has anything to do with it?

**Comment by EikeU** [comment]
@jamiemkass Thank you very much! Using maxent.jar did the trick, even when using more settings and variables. I also corrected the spelling error, thank you.

**Comment by EikeU** [comment]
Hello Jamie,

would you know if _var.importance()_ is still working or is going to be updated as well?

Thank you very much!

**Comment by jamiemkass** [comment]
@EikeU, great to hear maxent.jar worked. The function var.importance() only worked for maxent.jar because no one wrote similar functionality for maxnet, so I scrapped it for now. All it did was fetch the values from the Maxent object in dismo.

**Comment by EikeU** [comment]
@jamiemkass  Thank you. Do you know if there are plans to reinstate that function or a similar one?

I am asking because other functions to fetch variable importance ( like _maxentVarImp()_ ) don't work for me as the modelling output is an ENMeval object. And I am not good enough of an R user to be able to dismantle the ENMeval object to get to the Maxent object.

**Comment by jamiemkass** [comment]
For now, you can access this in the Maxent model object. When running with algorithm = "maxent.jar", you can get the model objects from an ENMevaluation result object called `e` either of these ways:

    # this gets the first model, corresponding to the first value in the e@results table
    eval.models(e)[[1]]
    # this lets you pick the model's name by pressing tab after the $
    e@models$fc.L_rm.1

You can then gets the results of the model, which is also mostly available in the html results file, this way:

     e@models$fc.L_rm.1@results

The permutation importance values are in there. Unfortunately, you can't do this with maxnet objects because there is no variable importance implemented. 

Hope this helps.

Jamie

**Comment by jamiemkass** [comment]
So glad I could help! No question about this stuff is too simple. If you have any more, please ask!
