### ISSUE TITLE
Projecting model computed with ENMevaluate() to future raster layers

### ISSUE THREAD

**Issue by KellumTJ** [jamiemkass/ENMeval#112]
Hi Jamie and ENMeval Co.,

Thanks all for this excellent package--I'm a relatively new R user and I have found it very user friendly. I'm running up against a problem with future predictions. I want to project a model built with the ENMevaluate() function to a RasterStack of future environmental variables (RCP8.5 for the year 2100). The goal of this projection is to estimate the range of my organism by the year 2100. I attempted to use the maxnet.predictRaster() function described here: https://github.com/jamiemkass/ENMeval/issues/64; however, this function does not appear to be present within the current version of the package (v 2.0.3) and I keep getting the following error message:

```
Error in maxnet.predictRaster() : 
  could not find function "maxnet.predictRaster"
```

I've read through all the comment boards, etc., that I can find, but have been unable to find a solution. Could you point me towards the correct function for using an ENMevaluation object to predict future range? Thank you in advance! Please let me know if there is any other information I can provide (this is my first GitHub question and I'm still learning the ropes).

In case it is helpful, here is my pertinent code up to this point:

```
cb1 <- get.checkerboard1(occs, envs.bg, bg, aggregation.factor = 5)

fc <- c("L", "LQ", "LQH", "H")

rm <- c(0.1, 0.25, 0.5, 1, 2, 4, 5)

e.mx.1 <- ENMevaluate(occs = occs, envs = envs, bg = bg, algorithm = 'maxnet',
                    partitions = 'checkerboard1', tune.args = list(fc = fc, rm = rm))

#Notation for "best" model using AICc criterion
aicmod <- which(e.mx.1@results$AICc == min(e.mx.1@results$AICc))
```

**Comment by jamiemkass** [comment]
@KellumTJ, this function was deprecated from ENMeval 2.x. The entire framework for specifying different models was changed to an object-oriented approach, where model specifications are now made through the ENMdetails object. Each algorithm has one. But these functions were programmed to operate internally, so it's a bit awkward to use them independently. I should probably recode them to make them more user-friendly. The reason we need them is because, for maxnet at least, there is no native predict function that takes and returns rasters. If there was, making predictions on your own would be much easier. 

If you look at enm.maxnet.R, this is an example of the ENMdetails specification for maxnet. The function `enm.maxnet@predict()` is used to make predictions for maxnet models. To use it outside of the internal ENMeval workflow, you could do: `enm.maxnet@predict(m, envs, NULL, list(args=c("outputformat=cloglog")))`, where `m` is your model and `envs` is a raster stack. The third argument is not used for maxnet, and the final one is an other.settings list that can specify the output format. However, this function sets clamp to FALSE by default (because internally clamping is done with clamp.vars()). Thus, make sure to clamp your variables with the `clamp.vars()` function before making a prediction. This function will return a raster prediction.

Sorry this is so cumbersome right now. In the next version, I'll make sure to make this more user friendly and add an example to the vignette.

**Comment by KellumTJ** [comment]
Hi Jamie,

Thank you for the prompt response! I really appreciate it. I've followed your instructions and I'm getting an output, but still having an issue. I would like to get a raster layer showing the predicted future range from with likelihood 0.0 - 1.0 like the output of the eval.predictions function, which shows the predicted modern range (code and figure shown below):

```
#This dplyr operation executes the sequential criteria
opt.seq <- res %>% 
  filter(or.10p.avg == min(or.10p.avg)) %>%
  filter(auc.val.avg == max(auc.val.avg))

#Select the model predictions for our optimal model
pred.seq <- eval.predictions(e.mx.1)[[opt.seq$tune.args]]
plot(pred.seq)
```


![image](https://user-images.githubusercontent.com/98131687/150592480-fde91865-2a62-4e0a-a4f3-36bf996d3eb6.png)

Beautiful! Just what I expected. However, when I run the enm.maxnet@predict function, I get a rather map with different units (not sure what they are). Below you will see the code I wrote from your instructions followed by the resulting map.

```
#Extract predictor variables values for the reference records; should ideally be the occurrences + background
ref.vals <- raster::extract(envs.bg, bg, method = 'simple', na.rm = TRUE)
  
#Clamp variables
f_envs <- clamp.vars(f_envs, ref.vals, left = NULL, right = NULL, categoricals = NULL)

#Future predictions for our optimal model
future <- enm.maxnet@predict(e.mx.1@models[[aicmod]], f_envs, NULL, 
                   list(args=c("outputformat=cloglog")))

plot(future)
```

![image](https://user-images.githubusercontent.com/98131687/150592829-b5e01849-a9b0-4c70-bf8c-3ac8289d08f5.png)

I would like to get a map for the future that, like the modern map, has range likelihood values from 0.0 - 1.0. From there, I should be set to go. Thank you again for your help--both I and my advisor really appreciate it!

**Comment by jamiemkass** [comment]
So sorry, I made a mistake. The arguments should be `future <- enm.maxnet@predict(e.mx.1@models[[aicmod]], f_envs, NULL, 
                   list(pred.type ="cloglog"))`. I gave you settings for a maxent.jar model by accident :P

The prediction you're seeing is the "exponential" prediction from maxnet, similar to maxent.jar's "raw" output, which can be interpreted at a relative occurrence rate (see Merow et al. 2013 paper on explaining Maxent).

**Comment by KellumTJ** [comment]
Woohoo, it's working! Thank you for your help Jamie, I really appreciate it!

**Comment by jamiemkass** [comment]
No problem! I hope to update the pkg soon so this is much more
straightforward.

**Comment by jamiemkass** [comment]
Just updated this in 9734ed3099f625939ab7671492330f3d4d10e1f2, so that you can run `future <- enm.maxnet@predict(e.mx.1@models[[aicmod]], f_envs, list(pred.type ="cloglog"))` (I removed the NULL argument). I also provide new examples in `?ENMevaluate` to demonstrate this functionality.
