### ISSUE TITLE
CBI NA values

### ISSUE THREAD

**Issue by marcelinedion** [jamiemkass/ENMeval#125]
When looking at the evaluation metrics of my enmEvaluate object, I get NA values in the CBI column for some of my models. Why is this? Am I safe to assume the NA models signify settings that are not ideal? I am running maxent.jar models FYI. Is there a way for me to see where the error is coming from or to verify where the NA values are being generated?

**Comment by jamiemkass** [comment]
CBI is NA when `ecospat::ecospat_boyce()` fails for some reason. This might be because of a weird point pattern, low data, etc. It is an indication that maybe something is not right with the data, but it could also be due to the partitions you selected that result in a training dataset that doesn't work with CBI. I would not assume that NA for CBI necessarily means a "bad model" though. Plot the prediction and the response curves to further investigate.

**Comment by marcelinedion** [comment]
Hi Jamie,

Thanks for the response -that all makes sense - is there a way to determine for sure what might be throwing the error? Or should I investigate the ecospat package more to determine what might be going wrong? Additionally do you have any resources I can look at regarding what I should be looking for in these response and prediction curves? Thanks I’m advance for any guidance you might be able to offer!

**Comment by jamiemkass** [comment]
Sorry for the late reply. I looked into this in detail once before by examining the code in ecospat, but it was a while ago. In simple terms, it has to do with the way the calculation of CBI necessitates binning and rebinning the data different ways, and I think if bins are missing data because of weird point patterns or small datasets, it might break. 

As for what to look for when you examine response curves, you need to use your expert opinion regarding your species and what seems most ecologically realistic. For example, if you have a positive linear response to increasing temperature, this is not realistic because at some high temp physiological limits kick in and the curve should go down. For predicting the training region, maybe this is not an issue because the temp doesn't get high enough, but if you transfer the model to other times or places with much higher temps, this model will produce spurious suitability predictions.
