### ISSUE TITLE
Sequential Model Selection Method

### ISSUE THREAD

**Issue by mclinx013** [jamiemkass/ENMeval#126]
Hello,

Sorry for another question! I am currently building models using the package but upon doing the sequential model selection method highlighted in the tutorial (OR10p & AUC), the model that appears to be the best is one with a high RM (5) that has all the environmental variables not contributing to the model. Is this a problem with my data? Or should I just discount any OR10p values that are equal to 0? I'm just at a loss... I am currently spatially blocking my data. Please see the attached picture for the distribution of occurrence points. Any guidance / advice would be very much appreciated - thank you!

<img width="400" alt="Screenshot 2022-05-29 at 20 47 03" src="https://user-images.githubusercontent.com/39660636/170888827-3e873573-bfce-46cd-b871-77615deaf022.png">
.

**Comment by jamiemkass** [comment]
Sorry for the late reply. Looks like you have a pretty sparse dataset that does not seem to be evenly sampled nor evenly distributed across the range. How many points do you have that are not grid-cell duplicates? Looks like maybe 7, at most 10? This is a very small dataset for a SDM, but not impossible to construct a model that may be useful in some way.

OR10p has an expected value of 0.1 (because it excludes the bottom 10% before selecting the minimum suitability score across the occurrence records), so 0 is better than expectation. However, zero omission might just mean the model has an extremely diffuse prediction that predicts most of the extent as suitable. This is why it's important to also look at CBI in these cases. CBI will be low if the spatial patterns of predicted suitability do not match expectation, which is high where occurrences are and lower where they are not. The problem is that you have such a small dataset that areas with low suitability where we have no occurrences will make CBI higher, but may in actuality represent areas where the species does exist but we simply need more sampling.

First off, I would not use block partitions for such a small dataset because the models will use only 3/4 of your already sparse data. Use jackknife instead, which maximizes the sample size per model. Second, I would run only simple models (L, maybe Q, only rm that is above 1, try to limit the number of predictors going in). Third, I'd be very cautious with any interpretation you make of the prediction because you have so few data points. Fourth, I'd consider using target-group background sampling if possible to account for the sampling bias.

Hope this helps!

**Comment by mclinx013** [comment]
Hello!

So sorry for my extremely slow response - however your reply is incredibly helpful and provides much guidance. Regarding the sparsity of our points, we are evaluating a hard to detect fungal species, thus the sparsity of the sample points. You have highlighted how close together the points themselves are - would it be unadvisable to keep all grid points in (as they are from different samples) even though they share close coordinates (with some overlapping coordinates or grid cells) ? I'd estimate we have 21 samples that do not share the same grid cell but are close together in range.

Finally, thank you again for the guidance. This is really quite helpful!

**Comment by jamiemkass** [comment]
I guess it depends how big your grid cells are. If they are very small, then you could have lots of grid cells with unique occurrences, but you'd have higher spatial autocorrelation between them due to stronger effects of sampling bias. If you use big cells, these effects will be lower but you'll have less data. I would tend to go the latter route. If you don't have enough data for a SDM, then don't use one. You could opt for something simpler like a convex hull to describe the distribution.
