### ISSUE TITLE
Function var.importance

### ISSUE THREAD

**Issue by uyhrt22zamora** [jamiemkass/ENMeval#135]
Hi, my name is Francisca and i´m having a trouble when try to use the function "var.importance"...
I´m new with this of codes and scripts, but i´ve tried uninstalling packages, updating, among other and nothing. The results is the same:
Error in var.importance() : could not find function "var.importance"
Is the function no longer available? or Are my librarys wrong?

Can you please help me :c?

**Comment by jamiemkass** [comment]
Sorry for the delay in my response. In recent versions, this function was deprecated, and now the way to do this for maxent.jar models is to use `eval.variable.importance(e)` for an ENMevaluation object. This only works for maxent.jar because maxnet has no native way to get variable importance, but it can be calculated with other packages.
