### ISSUE TITLE
Java heap space issues/GC overhead limits with ENMevaluate when running in paralllel

### ISSUE THREAD

**Issue by nikol-d97** [jamiemkass/ENMeval#145]
Hi there, 

Reporting an issue with running large-scale country wide models when setting parallelization in ENMevaluate to true: `parallel =  TRUE`. 

When running this code for species that tend to have large ranges (across all of Canada), the model fails to run with either a java heap space error, or a GC overhead limit error. Setting parallel equal to false seems to solve the issue, with the downside being a slower runtime. 

I am running these models using `maxent.jar` and have a 64GB ram machine. The error occurs when setting the model algorithm to `maxnet`.

**Comment by jamiemkass** [comment]
Thanks for the notice. Running with `maxnet` should not result in a Java error because it's not a Java program -- maxent.jar is though. I think you're probably getting the overhead limit error with `maxnet`, right? 

This might fix the Java heap space error: https://stackoverflow.com/questions/15399796/rjava-memory-error

Two things might be causing these errors. One is that you are likely specifying many features for the model and the fit becomes very complex, particularly for hinge, threshold, and product features. Trying running a model with L and Q only and see if you have similar problems. Product is notorious for making many (usually unnecessary) features because it creates all possible pairwise interactions -- if you're using this, I'd say drop it. Another possibility is that your rasters are high resolution and very big. See here for a possible fix: https://github.com/jamiemkass/ENMeval/issues/144

**Comment by nikol-d97** [comment]
Thanks Jamie! 

Yes that's correct, the error with `maxnet ` is the GC overhead limit error. 

I tested a variety of -xmx and -xms options and unfortunately none of them seemed to solve the heap space error. 

I suspect the culprit may be that the rasters are large and at a high resolution (1km) as the error tends to occur for larger ranging species (i.e., the majority of Canada). I do crop my rasters using a minimum convex polygon approach, but for some of the large ranging species the raster still may be too big. 

Setting the parallel option to false allows these large models to run without the heap space error, albeit quite slowly. I also noticed that when I set the parallel option to TRUE with `numCores = 1` >60% of my CPU power was being used up by the model with the java heap space error still occurring. I wonder why this was still happening with only 1 core being used? 

When setting the parallel option to false, only about 10% of my CPU power, and 50% of my RAM were being used for the same model.

**Comment by jamiemkass** [comment]
You might also try the species with data approach (SWD), which you can now specify in `ENMeval`. This way, you don't need to input the big rasters in maxent.jar, and once you select an optimal model, you can just make predictions for these rasters in R.
