### ISSUE TITLE
An unprecedented error!

### ISSUE THREAD

**Issue by momeni133** [jamiemkass/ENMeval#63]
Dear All,
I'm trying to find the best RM-FC for my MaxEnt run. 
In the past, I used the ENMeval package using below code, without any problem, but these days I receive an error which I never encountered with before. My code is:

`library(dismo)
library(rJava)
library(rgdal)
library(parallel)
library(ENMeval)

setwd("E:/winter_breeding/ENMeval")
fnamesEW <- list.files(path= "C:/Users/z/Desktop/winter_breeding/data/ASCII/2010_NA", pattern='asc', full.names=TRUE)
predictorsEW<- stack(fnamesEW)
Occ <- read.table("C:/Users/z/Desktop/winter_breeding/data/csv/winter_breeding.csv", header=TRUE, sep=',')[,-1]
background <- read.table("C:/Users/z/Desktop/winter_breeding/data/csv/background_20000.csv", header=TRUE, sep=',')
enmeval_results <-ENMevaluate(Occ, predictorsEW, bg.coords = background, 
                                           method = "checkerboard2", overlap = FALSE, RMvalues=c(0.5,1,1.5,2,2.5,3,3.5,4,4.5,5,5.5,6,6.5,7,7.5,8,8.5,9,9.5,10), fc = c("L","H", "LQ", "LQH", "LQHP"),
                                           bin.output = FALSE, parallel = TRUE)`

The error massage is:
" Error in file(fn, "rb") : cannot open the connection
In addition: Warning message:
In file(fn, "rb") :
  cannot open file 'C:\Users\z\AppData\Local\Temp\Rtmpi2yNtc\raster\r_tmp_2018-11-26_173437_17524_09081.gri': No such file or directory"

Could you please help me to solve this problem?
I'm using MaxEnt 3.4.1 in ENMeval v 0.2.2. I also tried the latest version of ENMeval by both algorithms but the error persists.

Best,
Iman

**Comment by krypttr** [comment]
I have  the same issue.

**Comment by bobmuscarella** [comment]
We are wondering if this has to do with the size of the raster files.  Can you try your analysis with a subset of your study extent and see what happens?

**Comment by momeni133** [comment]
I tried with only 2 RM values and 2 FCs, but the problem persists.
Now, I am trying to run it in a small geographic area and will inform you soon about the result.

**Comment by momeni133** [comment]
With a small geographical area, it works perfectly.
Do you have any suggestion?
I cannot divide my study area. 
Any solution to solve this problem?
I think my computer is fast enough. It has 24 Gb RAM ddr4, CPU = Core i7 6th generation, SSD with more than 70 Gb free space in the working directory and also the operating system.

**Comment by bobmuscarella** [comment]
Hi Iman,

Thanks for the report back.  I'm glad it helps avoid the error but too bad
it doesn't solve your problem.  I'm not really sure of the best solution.
I know I have seen some stuff on how you can get your computer to allocate
more memory to java programs.  See, for example:
https://groups.google.com/forum/#!topic/maxent/BkWA8QjVlnA
and
https://groups.google.com/forum/#!topic/maxent/FGOXMNgr8Tw

See also the Note section of the maxent function documentation (do
?dismo::maxent in R).  Perhaps changing the memory allocation would help?

Another possible workaround may be to set the rasterPreds argument to
FALSE.  I'm not sure if this will avoid the problem but may be worth a
try.  Otherwise, I'm not really sure about the solution - sorry I can't
be of more help!

Good luck!
Bob

**Comment by momeni133** [comment]
Thanks Bob,
If I turn the rasterPreds off, will ENMeval be able to calculate AICc?

**Comment by bobmuscarella** [comment]
No, AICc is not calculated if rasterPreds=FALSE because these calculations
require the predicted surfaces.  But if all you want is AIC then you could
probably write up a fairly simple loop that bypasses all the data
partitioning stuff ENMeval does...  The AIC values ENMeval calculates are
based on the unpartitioned model (i.e., the model made with all the data).

**Comment by krypttr** [comment]
@momeni133 can you try `memory.limit(memory.limit() * 2^30)` This seems to help.

**Comment by momeni133** [comment]
Dear Bob and krypttr,
Thanks a lot. 
I'll try these and will inform you.

**Comment by BenMMarshall** [comment]
I have come across a very similar issue when running the ENMevaluate() function. Would run without issue for smaller extents, but scaled up I would see similar "Error in file(fn, "rb") : cannot open the connection" messages. This was while using ENMeval_0.3.0.
I managed to get around it without changing any output settings (ie still getting prediction rasters, AICc etc); instead telling it not to run in parallel. That's likely not a feasible option for everyone, but for the limited model running I was doing, waiting much longer wasn't too much of an issue. Clumsy solution to get around a memory limitation but it worked for me.

**Comment by rkirstentyler** [comment]
> Dear Bob and krypttr,
> Thanks a lot.
> I'll try these and will inform you.

@momeni133 did you ever figure this out?

**Comment by jamiemkass** [comment]
Can you confirm whether this is still a problem after updating all packages, including ENMeval to 2.0.0? If so, I can look into it.

Jamie
