### ISSUE TITLE
Testing AUC using independent background locations

### ISSUE THREAD

**Issue by elgabbas** [jamiemkass/ENMeval#71]
Hello,
This may be a question rather than an issue.
I am a bit confused why testing AUC is calculated by contrasting testing presences against the whole background locations all over the study area, not only background locations at the testing folds? Is there a reason for that?

https://github.com/bobmuscarella/ENMeval/blob/325e686b6f72413a443e9c8291e63867bd9ebd13/R/modelTune.maxentJar.R#L34-L36
https://github.com/bobmuscarella/ENMeval/blob/325e686b6f72413a443e9c8291e63867bd9ebd13/R/modelTune.maxentJar.R#L44-L45

Cheers,
Ahmed

**Comment by ndimhypervol** [comment]
This is referred to in the ENMeval software note: "Importantly, for the geographically structured partitioning methods, background localities in the same geographic area as the bin holding testing localities are not included in the training phase (Phillips 2008; Phillips & Dudík 2008; Radosavljevic & Anderson 2014)." But there is no explicit mention of which background is used to calculate AUC test and why in this paper, nor in Radosavljevic & Anderson (2014). 

It's a good question, and I'm not sure this is one right answer. When we are averaging AUC test values across all spatial partitions, we are  determining how well on average the model is at predicting spatially withheld data from random samples from the study extent the full model is trained on (full background). For each partition, the test presences are outside the training extent, and thus may have different environmental distributions than those of the training extent, so the model is expected to do somewhat poorly predicting them compared to training presences. Thus, there is a theoretical expectation here given test presences and training background. I'm not sure what the expectation is given test data and test background. Should the model do better or worse discerning unknown test data from unknown background data? 

A different question is should we evaluate test data against the full background or just the training background? I suppose the interpretation would change for this configuration as well.

I welcome anyone else to contribute, because I find this topic interesting, and I don't have concrete answers here.

Jamie

**Comment by bobmuscarella** [comment]
Forwarding this to Rob Anderson as he may have good input on the question...

**Comment by bobmuscarella** [comment]
It is an imperfect solution to a thorny issue. From p. 634 of Radosavljevic and Anderson 2014:


Valid comparisons with the other approaches (and subtraction of evaluation AUC from calibration AUC) require a non-traditional modification of calibration AUC for the masked geographically structured approach, in which the calibration regions differ among the k iterations as well as from those of the other two approaches. Therefore, we calculated both evaluation and calibration AUCs over the full study region and calculated averages as above.


*************************************

Robert P. Anderson, Ph.D.

Professor, Department of Biology

526 Marshak Science Building

City College of New York, City Univ. of New York

160 Convent Avenue

New York, NY 10031 USA



Telephone: (212) 650-8504

http://www.andersonlab.ccny.cuny.edu/<http://web.sci.ccny.cuny.edu/~anderson/>

________________________________
From: Bob Muscarella <bob.muscarella@gmail.com>
Sent: Tuesday, April 30, 2019 6:19 AM
To: Robert Anderson; bobmuscarella/ENMeval
Cc: Subscribed; bobmuscarella/ENMeval
Subject: [EXTERNAL] Re: [bobmuscarella/ENMeval] Testing AUC using independent background locations (#71)

Forwarding this to Rob Anderson as he may have good input on the question...


On Tue, 30 Apr 2019 at 08:02, Jamie M. Kass <notifications@github.com<mailto:notifications@github.com>> wrote:

This is referred to in the ENMeval software note: "Importantly, for the geographically structured partitioning methods, background localities in the same geographic area as the bin holding testing localities are not included in the training phase (Phillips 2008; Phillips & Dudík 2008; Radosavljevic & Anderson 2014)." But there is no explicit mention of which background is used to calculate AUC test and why in this paper, nor in Radosavljevic & Anderson (2014).

It's a good question, and I'm not sure this is one right answer. When we are averaging AUC test values across all spatial partitions, we are determining how well on average the model is at predicting spatially withheld data from random samples from the study extent the full model is trained on (full background). For each partition, the test presences are outside the training extent, and thus may have different environmental distributions than those of the training extent, so the model is expected to do somewhat poorly predicting them compared to training presences. Thus, there is a theoretical expectation here given test presences and training background. I'm not sure what the expectation is given test data and test background. Should the model do better or worse discerning unknown test data from unknown background data?

A different question is should we evaluate test data against the full background or just the training background? I suppose the interpretation would change for this configuration as well.

I welcome anyone else to contribute, because I find this topic interesting, and I don't have concrete answers here.

Jamie

-

**Comment by elgabbas** [comment]
Thanks Bob and Jamie,

So, do you think that [Radosavljevic and Anderson 2014](https://onlinelibrary.wiley.com/doi/10.1111/jbi.12227) calculated AUC<sub>test</sub> this way only to make comparisons with other evaluations valid. If so, this makes sense to me.

But, if we're not interested in compiring AUC<sub>test</sub> with AUC<sub>full</sub> or AUC<sub>training</sub> or other metrics, do not you think that it is more logical to calculate AUC<sub>test</sub> by contrasting testing presences against testing background? The over all background locations are not spatially-independent from those used to train the model. 

By calculating AUC<sub>test</sub> using all background locations, I think AUC<sub>test</sub> may depend on how environmentally-dissimilar are the testing presences than the over all background locations across the study area. In extremely large study areas, for example, some testing bins may contain testing presences highly environmentally-dissimilar than the over all background locations, then we may get high AUC<sub>test</sub> scores only because of this.

I could not find any other papers discussed this, but please have a look over figure 7 of [Fithian _et al._ ](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12242)'s paper. 

I calculated AUC<sub>test</sub> only from left-out fold (presence/background) in two paper out of my PhD [[10.1111/ecog.03149](https://www.biom.uni-freiburg.de/mitarbeiter/dormann/el-gabbas2018ecography.pdf) and [10.1002/ece3.3834](https://www.biom.uni-freiburg.de/mitarbeiter/dormann/el-gabbas2018ecolevol.pdf)].

Cheers,
Ahmed

**Comment by ndimhypervol** [comment]
@elgabbas So sorry for the long delay -- I had meant to reserve time to think about this and then got caught up with other things. You make a very good point. The Radosavljevic & Anderson 2014 paper seems to have made the decision to calculate AUCtest using the full training background to compare between different approaches for their study, and this decision was carried over to ENMeval. However, the interpretation certainly changes for each way AUCtest is calculated. For each, you are measuring the ability of the model to discriminate between spatially independent occurrences and:

spatially blocked training background: just the environments the model knows and are not associated with the testing occurrences

spatially blocked testing background: just the environments the model theoretically does not know (as well) and are associated with the testing occurrences

full background: a mixture of environments the models knows (spatially blocked training background) and those it theoretically does not (spatially blocked testing background) that are both associated and not associated with the testing occurrences

In simpler language, what does this mean?

spatially blocked training background: How well can the model discern occurrences from other areas from the region the model is built with?

spatially blocked testing background: How well can the model discern occurrences from other areas from the region surrounding these occurrences?

full background: How well can the model discern occurrences from other areas from the entire region?

Maybe this makes the interpretations a bit easier to understand (the exercise of writing them out was informative for me). It doesn't help me come to a decision as to which is definitively the most appropriate in general. Perhaps reporting them all, or just the spatially blocked versions, is best? I do understand completely why you chose to calculate AUCtest from the left-out fold in your papers, and I think it's a valid evaluation. I am considering now adding a parameter to the new version of ENMeval that allows you to choose how AUCtest is calculated for spatially blocked CV.

Regardless, thanks for the questions, and please get back if you can with your thoughts.

**Comment by DevinALyons** [comment]
Hi,
I have a somewhat related question but I also wanted to note that I also think this is an important issue. I wish there was greater clarity but it remains unclear to me what the "right" or "best" way to deal with the background in AUC calculations for spatial folds. I can see both sides....it seems to make sense to use independent background data, but then the background data is meant to characterize the environment the species "could" have been observed in and using a small, spatially clustered subset is going likely to make for a smaller, skewed distribution of background conditions. I can't really decide if this is desirable or not. In any case, from my reading, it seems like Radosavljevic & Anderson 2014 altered the AUC calculation for their masked geographically structured cross-validation results, not for all AUC calculations. So perhaps this isn't the best approach to be used for all AUC calculations?  

Ok, so my question.....in a similar way to the AUC calculation using the entire background, I noticed that, for the k-folds cross-validation method, background locations are appear not to be assigned to a fold but are instead all assigned to group 0. This means that the entire background is used in the training and testing (and AUC caclulations) for each fold. It would seem to make sense for background data to be independent in the different folds. Is there a reason not to do this? Does anyone know if this is what the maxent java program does?

**Comment by ndimhypervol** [comment]
From my understanding, the Maxent Java program does not partition the background at all when doing cross validation. Partitioning the background makes sense for spatial blocks because you want the training data to exclude the background associated with the withheld block in order to keep the conditions there "novel" to the model for evaluation. For random k-fold cross validation, the folds should all be more or less representative of the entire study extent (unless you have very few data points and stochastically the sampling results in big spatial gaps for some folds). Thus, partitioning the background rarely makes sense for non-spatial blocking.

Regarding the "best" way to calculate metrics like AUC or the continuous Boyce index when the background is partitioned, I don't think anyone's explored that yet -- though this remains worth exploring! The new version of ENMeval (currently in dev) allows the user to choose whether to use the full background or just the partition background, though we make no suggestions as to which is better. I added this option because of the interesting conversation in this Issue, and I considered that including it would allow others to examine differences in the metrics, perhaps leading them to make a decision which to choose for their study.

**Comment by DevinALyons** [comment]
Thanks for responding.

On background partitioning (or not), I can see how the use of background data instead of absences MIGHT make it allowable to reuse data points in multiple folds, but it still seems kind of questionable. For random k-folds, it also seems unnecessary to not partition for the reasons you mention.... a sufficiently large sample (of pseudo absences) should ensure that you cover the range(s) of the data and reflect the distributions of the environmental data pretty well in each testing and training fold. So it would have made sense to me to partition just to be safe. 

It'd be nice if some stats-theory justification could be made to help guide some of these decisions.....lacking that, I'd like to see some extensive work with virtual species that would at lease help provide hints for the best thing to do under different scenarios.

**Comment by jamiemkass** [comment]
I completely agree! This topic doesn't get enough attention, probably because it's kind of boring, but it is nonetheless important. We tried to be as flexible as we could with spatial partition background use for evaluations in the new version, but perhaps in future versions the same should be done with random k-fold as well? Not sure, but good to think about it.
